[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1f2937"
textColor = "#f8fafc"
font = "sans serif"

[ui]
hideTopBar = false

[server]
headless = true

[client]
showSidebarNavigation = false
